repositories:
- name: digit-backbone
  url: https://helm.digit.org/backbone

templates: 
  backbone: &backbone
    namespace: backbone
    missingFileHandler: Warn

values:
- {{ env "ENV_FILE" }} 
- {{ env "SECRET_FILE" }} 

releases:
- name: cert-manager
  chart: digit-backbone/{{`{{ .Release.Name }}`}}
  namespace: egov
  installed: true
  version: 1.0.0
  disableValidation: true

# - name: minio
#   installed: true
#   chart: ./minio
#   version: 13.3.1
#   <<: *backbone
#   values:
#     - ./minio/values.yaml

# - name: postgresql
#   installed: true
#   chart: ./postgresql
#   version: 11.9.13
#   <<: *backbone
#   values:
#     - ./postgresql/values.yaml
#     - global:
#         postgresql:
#           auth:
#             postgresPassword: {{ .Values.secrets.db.password | quote }}

- name: redis
  installed: true
  chart: digit-backbone/{{`{{ .Release.Name }}`}}
  version: 3.0.0
  <<: *backbone

- name: elasticsearch-master
  chart: digit-backbone/{{`{{ .Release.Name }}`}}
  version: 1.0.0
  <<: *backbone
  values:
    - secret:
        password: {{ .Values.secrets.elasticsearch.password }}

- name: elasticsearch-data
  chart: digit-backbone/{{`{{ .Release.Name }}`}}
  version: 1.0.0
  <<: *backbone

- name: kibana
  chart: digit-backbone/{{`{{ .Release.Name }}`}}
  version: 1.0.1
  force: true
  <<: *backbone
  values:
    - ingress:
        hosts:
          - host: {{ .Values.global.domain }}
            paths:
              - path: /kibana
        pathtype: Prefix
        tls: 
          - secretName: {{ .Values.global.domain }}-tls-certs
            hosts:
              - {{ .Values.global.domain }}

- name: kafka-kraft
  installed: true
  chart: digit-backbone/{{`{{ .Release.Name }}`}}
  version: 1.0.0
  <<: *backbone

- name: ingress-nginx
  installed: true
  chart: digit-backbone/{{`{{ .Release.Name }}`}}
  version: 1.0.0
  <<: *backbone
  values:
    - domain: {{ .Values.global.domain }}

# - name: playground
#   installed: true
#   chart: ./playground
#   version: 0.1.0
#   <<: *backbone
#   values:
#     - ./playground/values.yaml