name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for pushing to another branch

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Package Helm chart
        run: |
          helm package charts/urban-test --destination ./

      - name: Generate/update Helm repo index
        run: |
          helm repo index . --url https://egovernments.github.io/urban-helm-charts/

      - name: Push chart and index to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: packages/
          force_orphan: true  # Optional: overwrites old content
