name: Publish Helm Chart

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to get all history for `git describe`

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "3.13.3" # Specify a version or use "latest"

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run Helm package
        run: |
          CHART_VERSION=$(helm show chart charts/my-chart | grep "version: " | awk '{print $2}') #getting the version from the Chart.yaml file
          echo "::set-output name=chart_version::$CHART_VERSION"
          helm package charts/my-chart -d . # Packages the chart into a .tgz archive

      - name: Create gh-pages branch if it doesn't exist
        run: |
          git fetch origin
          if [[ $(git ls-remote --heads origin gh-pages) ]]; then
            echo "gh-pages branch exists"
          else
            echo "gh-pages branch does not exist, creating it"
            git checkout --orphan gh-pages
            git commit --allow-empty -m "Initial commit for gh-pages"
            git push origin gh-pages
          fi

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Helm package to packages directory
        run: |
          mkdir -p gh-pages/packages
          cp *.tgz gh-pages/packages/

      - name: Update index.yaml
        run: |
          helm repo index gh-pages/packages --url https://egovernments.github.io/urban-helm-charts/packages/ # change the repo url

      - name: Commit and push changes to gh-pages
        run: |
          cd gh-pages
          git add .
          git commit -m "Update Helm chart package and index"
          git push origin gh-pages
      - name: Delete the generated tgz file
        run: |
          rm *.tgz
