name: Publish Helm Charts

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Package Helm charts
        run: |
          mkdir -p chart-packages
          for chart in charts/*/; do
            helm package "$chart" --destination chart-packages
          done

      - name: Generate index.yaml
        run: |
          mkdir -p gh-pages/packages # Create the directory before indexing
          helm repo index chart-packages --url https://${{ github.repository_owner }}.github.io/urban-helm-charts/packages

      - name: Push to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages

          mkdir -p gh-pages/packages
          cp chart-packages/*.tgz gh-pages/packages/
          cp chart-packages/index.yaml gh-pages/packages/
          touch gh-pages/.nojekyll

          cd gh-pages
          git add .nojekyll packages/
          git commit -m "Update Helm charts" || echo "No changes to commit"
          git push origin gh-pages
