name: Publish Helm Charts to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package all Helm charts
        run: |
          mkdir -p chart-packages
          for dir in charts/*/; do
            helm package "$dir" --destination chart-packages
          done

      - name: Generate Helm index.yaml
        run: |
          helm repo index chart-packages --url https://${{ github.repository_owner }}.github.io/urban-helm-charts/packages

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy packaged charts and index to gh-pages
        run: |
          mkdir -p gh-pages/packages
          cp chart-packages/*.tgz gh-pages/packages/
          cp chart-packages/index.yaml gh-pages/packages/

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add packages
          git commit -m "Update Helm chart packages" || echo "No changes"
          git push origin gh-pages
