name: Publish Helm Charts

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        run: |
          git clone https://github.com/egovernments/urban-helm-charts.git .
          git checkout master

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Package Helm charts
        run: |
          mkdir -p chart-packages
          for chart in charts/*/; do
            helm package "$chart" --destination chart-packages
          done

      - name: Generate index.yaml
        run: |
          helm repo index chart-packages --url https://egovernments.github.io/urban-helm-charts/packages

      - name: Push to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Clone gh-pages into a subdirectory
          git clone --branch gh-pages https://github.com/egovernments/urban-helm-charts.git gh-pages

          # Copy files
          mkdir -p gh-pages/packages
          cp chart-packages/*.tgz gh-pages/packages/
          cp chart-packages/index.yaml gh-pages/packages/

          cd gh-pages
          git add packages
          git commit -m "Update Helm charts" || echo "No changes to commit"
          git push origin gh-pages
