# .github/workflows/helm-publish.yml
name: Publish Helm Chart to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'urban-test/**' # path to your Helm chart

jobs:
  publish-helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm chart
        run: |
          mkdir -p chart-packages
          helm package urban-test --destination chart-packages

      - name: Generate Helm index.yaml
        run: |
          helm repo index chart-packages --url https://${{ github.repository_owner }}.github.io/urban-helm-charts

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy packaged chart and index
        run: |
          mkdir -p gh-pages/packages
          cp chart-packages/*.tgz gh-pages/packages/
          cp chart-packages/index.yaml gh-pages/packages/index.yaml

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add packages
          git commit -m "Update Helm charts" || echo "No changes to commit"
          git push origin gh-pages
