name: Publish Helm Charts

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to get all history for `git describe`

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "3.13.3" # Specify a version or use "latest"

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get changed charts
        id: changed-charts
        run: |
          CHANGED_CHARTS=$(git diff --name-only HEAD^ HEAD | grep '^charts/' | cut -d'/' -f2 | uniq)
          echo "::set-output name=changed_charts::$CHANGED_CHARTS"

      - name: Package and copy charts
        run: |
          mkdir -p packaged_charts
          for chart in ${{ steps.changed-charts.outputs.changed_charts }}; do
            echo "Packaging chart: charts/$chart"
            helm package charts/$chart -d packaged_charts
          done

      - name: Create gh-pages branch if it doesn't exist
        run: |
          git fetch origin
          if [[ $(git ls-remote --heads origin gh-pages) ]]; then
            echo "gh-pages branch exists"
          else
            echo "gh-pages branch does not exist, creating it"
            git checkout --orphan gh-pages
            git commit --allow-empty -m "Initial commit for gh-pages"
            git push origin gh-pages
          fi

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Helm packages to packages directory
        run: |
          mkdir -p gh-pages/packages
          cp packaged_charts/*.tgz gh-pages/packages/

      - name: Update index.yaml
        run: |
          helm repo index gh-pages/packages --url https://egovernments.github.io/urban-helm-charts/packages/ # change the repo url

      - name: Commit and push changes to gh-pages
        run: |
          cd gh-pages
          git add .
          git commit -m "Update Helm chart packages and index"
          git push origin gh-pages

      - name: Delete the generated tgz files
        run: |
          rm packaged_charts/*.tgz
