repositories:
- name: core
  url: https://helm.digit.org/core

templates:
  core: &core
    chart: core/{{`{{ .Release.Name }}`}}
    version: 0.1.0
    namespace: playground
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    values:
      - {{ .Values | toYaml | nindent 8 }}
    # secrets:
    #   - ../../env-templates/env-secrets.yaml  

values:
- {{ env "ENV_FILE" }} 
- {{ env "SECRET_FILE" }} 
 

releases:
- name: egov-accesscontrol # Replace with your desired namespace
  installed: true # Replace with the version of your chart, if needed
  <<: *core

- name: audit-service # Replace with your desired namespace
  installed: true # Replace with the version of your chart, if needed
  <<: *core

- name: egov-enc-service # Replace with your desired namespace
  installed: true
  needs:
  - egov-mdms-service
  <<: *core

- name: egov-filestore # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-idgen # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-localization # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-location # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-mdms-service # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-hrms # Replace with your desired namespace
  installed: true
  needs:
  - egov-user
  <<: *core

- name: egov-indexer # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-notification-mail # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-notification-sms # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-user # Replace with your desired namespace
  installed: true
  needs:
  - egov-enc-service
  <<: *core

- name: egov-otp # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-persister # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-url-shortening # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-workflow-v2 # Replace with your desired namespace
  installed: true
  needs:
  - egov-mdms-service
  <<: *core

- name: user-otp # Replace with your desired namespace
  installed: true
  <<: *core

- name: configmaps # Replace with your desired namespace
  installed: true
  <<: *core

- name: citizen # Replace with your desired namespace
  installed: true
  <<: *core

- name: digit-ui # Replace with your desired namespace
  installed: true
  <<: *core

- name: service-request # Replace with your desired namespace
  installed: true
  <<: *core

- name: egov-pg-service # Replace with your desired namespace
  installed: true
  <<: *core
  
- name: egov-user-event # Replace with your desired namespace
  installed: true
  <<: *core

- name: gateway # Replace with your desired namespace
  installed: true
  <<: *core


