# Common Labels
labels:
  app: "auth-proxy"
  group: "rainmaker"

namespace: es-upgrade

# Container Configs
image:
  repository: "egovio/auth-proxy:auth-proxy-urlencoded-fix-aad9a5959c-23"
replicas: "1"
appType: "java-spring"
tracing-enabled: true

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_USER_SEARCH
    value: "user/_details"
  - name: KIBANA_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kibana-host
  - name: KIBANA_BASE_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kibana-base-path
  - name: KIBANA_ACCEPTED_CONTEXT_UI_PATHS
    value: "workbench-ui,sanitation-ui,works-ui,digit-ui"
  - name: KIBANA_ACCEPTED_DOMAIN_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: domain
  - name: KIBANA_EXCLUDE_URL_PATTERNS
    value: ".js,.css,.html,fonts,favicons,telemetry"
  